### ISSUE TITLE
Flatten is not activating!

### ISSUE THREAD

**Issue by SamSSupreme** [bunsenstraat/flattener#5]
Internal server error in writing there instead of flatten contract

**Comment by R1NER** [comment]
Same. Yesterday it was fine, but now this problem occurs...
![image](https://user-images.githubusercontent.com/44713803/156921698-2bb10c5f-4c61-4fca-91fa-485be40db3d6.png)

**Comment by Evgeniy-Gorshkov** [comment]
same error, yesterday everything worked. Who knows if there is an alternative for Remix ide?

**Comment by Fdarawsheh** [comment]
has this been fixed yet ?

**Comment by Evgeniy-Gorshkov** [comment]
no

**Comment by Fdarawsheh** [comment]
well that's bothersom. know of any other resource that I can use to flatten a contract?

**Comment by SamSSupreme** [comment]
Maybe admin @bunsenstraat  is going to fix it, please

**Comment by ax0x0** [comment]
also having issue

**Comment by Xigrealf** [comment]
Having the same issue currently hopefully it will get fixed soon.

**Comment by plytki** [comment]
Here you have an emergency flattener plugin if it fails again.
[](https://remix-flattener.plytki.dev/)

**Comment by Larry526** [comment]
how do I use this emergency plugin?

**Comment by plytki** [comment]
> how do I use this emergency plugin?

![Screenshot_20220308-010139](https://user-images.githubusercontent.com/53957038/157139132-472eccc1-9f8e-4378-90a7-22566f6fdb63.jpg)
![Screenshot_20220308-010249](https://user-images.githubusercontent.com/53957038/157139150-06c60d5e-7611-4b8f-8780-90a65b42ea56.jpg)

**Comment by Larry526** [comment]
thanks you! btw its back online

**Comment by bunsenstraat** [comment]
IPFS had troubles. that's why it happened. Working on a solution.
